# Configuration for Video Generation arxiv daily
max_results: 20

# publishing flags
publish_readme: true
publish_gitpage: false
publish_wechat: false
show_badge: true
update_paper_links: false
enable_github_search: false

# file paths
json_readme_path: './docs/vg-arxiv-daily.json'
md_readme_path: 'README.md'
json_gitpage_path: './docs/vg-arxiv-daily-web.json'
md_gitpage_path: './docs/index.md'
json_wechat_path: './docs/vg-arxiv-daily-wechat.json'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Video Generation":
        filters: ["Text-to-Video", "Text2Video", "Video Transformer", "Physically Plausible video", "Physics Consistency video", "physics video", "image-to-video", "video diffusion model", "video generation model"]
