# Configuration for Video Generation arxiv daily
max_results: 1000

# file paths
json_readme_path: './docs/vg-arxiv-daily.json'
md_readme_path: 'README.md'

# keywords to search
keywords:
    "Video Generation":
        filters: ["Text-to-Video", "Text2Video", "Video Transformer", "Physically Plausible video", "Physics Consistency video", "physics video", "image-to-video", "video diffusion model", "video generation model"]
