# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "liutaocode"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 1000

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/vg-arxiv-daily.json'
json_gitpage_path: './docs/vg-arxiv-daily-web.json'
json_wechat_path: './docs/vg-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Video Generation":
        filters: ["Text-to-Video", "Text2Video", "Video Transformer", "Physically Plausible video", "Physics Consistency video", "physics video", "image-to-video", "video diffusion model", "video generation model"]


