name: Daily arXiv Update

on:
  schedule:
    # Run at 0:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-papers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install arxiv pyyaml requests beautifulsoup4
        
    - name: Run daily update
      run: |
        python daily_arxiv.py
        
    - name: Check for changes
      id: verify_diff
      run: |
        git diff --quiet . || echo "changes=true" >> $GITHUB_OUTPUT
        
    - name: Commit and push if changed
      if: steps.verify_diff.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Daily arXiv update $(date +'%Y-%m-%d')"
        git push